name: Python Convention Check

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  style_check:
    name: Check Python Code Convention
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.19.2
